folder('AWS'){
    displayName('AWS')
    description('AWS')
}
folder('AWS/NETWORKING'){
    displayName('NETWORKING')
    description('NETWORKING')
}
folder('AWS/NETWORKING/NOPROD'){
    displayName('NOPROD')
    description('NOPROD')
}
folder('AWS/NETWORKING/PROD'){
    displayName('PROD')
    description('PROD')
}
folder('AWS/INFRA'){
    displayName('INFRA')
    description('INFRA')
}

folder('AWS/INFRA/NOPROD'){
    displayName('NOPROD')
    description('NOPROD')
}
folder('AWS/INFRA/PROD'){
    displayName('PROD')
    description('PROD')
}